#application.yml
management:
  endpoints:
    web.exposure.include: health,metrics

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost/demo
    username: postgres
    password: passw0rd
    initialization-mode: always